# Generated by Django 6.0.1 on 2026-01-12 14:24

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Business_Name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Updated_Photo',
        ),
        migrations.RemoveField(
            model_name='account',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='account',
            name='website_Url',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updated_Photo', models.ImageField(blank=True, null=True, upload_to='images/', validators=[accounts.models.validate_image])),
                ('Business_Name', models.CharField(blank=True, max_length=50)),
                ('Website_Url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
